### ISSUE TITLE
Add Kestra App Resource

### ISSUE THREAD

**Issue by japerry911** [kestra-io/terraform-provider-kestra#143] opened 2024-12-13 20:46 UTC
### Feature description

- Add Kestra App Resource please 
- goal would be to manage app YAML code with Version Control and Terraform :D

**Comment by Ben8t** [comment] 2024-12-16 08:24
duplicate of https://github.com/kestra-io/kestra-ee/issues/2294 😉 closing this one

**Closed by Ben8t** 2024-12-16 08:24 UTC
Labels: enhancement
